name: turbo_template_env    # 设置容器组名称

networks:  #创建网络
  template_net:
volumes: #创建挂载卷
  reids_data:
  postgresql_data:
  api_data:
  frontend_data:
  backend_data:
services:  # 定义服务组
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/backend.env.dockerfile
      network: host
    volumes:
      - 'backend_data:/app/apps/backend/public'
    restart: always
    ports:
      - 3103:3000
    networks:
      - template_net
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/frontend.env.dockerfile
      network: host
    volumes:
      - 'frontend_data:/app/apps/frontend/public'
    restart: always
    ports:
      - 3102:3000
    networks:
      - template_net
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: ./apps/api/api.env.dockerfile
      network: host
    volumes:
      - 'api_data:/app/apps/api/public'
    restart: always
    ports:
      - 3101:3000
    networks:
      - template_net
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    restart: always
    shm_size: 128mb # 设置共享内存最小值
    ports:
      - '5032:5432'
    expose:
      - 5032
    environment:   # 设置环境变量
      POSTGRES_USER: turbo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: turbo_temp
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'   # 挂载数据到指定路径
    networks:
      - template_net
    depends_on: # 设置依赖项
      - redis  # 设置redis为依赖，只有redis启动成功后在启动
  redis:  # redis容器
    image: redis:7.2  # 镜像+tag
    restart: always  # 同步重启
    command: redis-server --save 60 1 --loglevel warning --appendonly yes  #设置redis-server
    ports:
      - '6079:6379'  # 指定端口
    volumes:   # 设置挂在卷
      - 'reids_data:/data'   # 将redis数据挂载到指定路径
    networks: # 设置网络归属
      - template_net